# Generated by Django 5.0.6 on 2024-08-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_culture_housing_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
