# Generated by Django 5.0.6 on 2024-08-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_culture_image_housing_image_transport_image_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'recipient'], name='authenticat_sender__baba19_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp'], name='authenticat_timesta_c13f17_idx'),
        ),
    ]
