# Generated by Django 5.0.6 on 2024-08-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='test_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
