# Generated by Django 5.0.6 on 2024-08-07 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_customuser_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='test_field',
        ),
    ]
