# Generated by Django 5.0.6 on 2024-08-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_userprofile_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='zip_code',
        ),
    ]
