# Generated by Django 5.2.1 on 2025-05-31 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_userprofile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
