EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'studentkonnect43@gmail.com'
# EMAIL_HOST_PASSWORD = 'ztjgxsoeuidfpung'
EMAIL_HOST_USER = 'studentskonnect49@gmail.com'
EMAIL_HOST_PASSWORD = 'sbpburjfslhtmqvl'
# EMAIL_USE_SSL = False